name: Check PR code coverage

on:
  pull_request:

jobs:
  build:
    runs-on: macos-14
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v3
      - name: Change wrapper permissions
        run: chmod +x ./gradlew
      - name: Gradle tasks
        shell: bash
        run: ./gradlew tasks --all